export const appProperties = {
  // userServiceEndPoint: "https://127.0.0.1:5011/",
  // userServiceEndPoint: "http://socialmediauserservice-env.eba-mypq7pxk.us-east-1.elasticbeanstalk.com/",
  userServiceEndPoint: "https://lgwxyktbpd.execute-api.us-east-2.amazonaws.com/prod/user/",
  //userServiceEndPoint: "https://d7dl8k2ursld3.cloudfront.net/user/",
  // postServiceEndPoint: "http://https://54.172.1.203:5011/al-media-post.us-east-2.elasticbeanstalk.com/",
  postServiceEndPoint: "https://lgwxyktbpd.execute-api.us-east-2.amazonaws.com/prod/",
  //postServiceEndPoint: "https://d7dl8k2ursld3.cloudfront.net/",
  // commentServiceEndPoint: "http://127.0.0.1:5012/",
  commentServiceEndPoint: "https://lgwxyktbpd.execute-api.us-east-2.amazonaws.com/prod/",
  //commentServiceEndPoint: "https://d7dl8k2ursld3.cloudfront.net/",
  // feedServiceEndPoint: "http://socialmediafeed-env.eba-ait8ygdw.us-east-2.elasticbeanstalk.com",
  // feedServiceEndPoint: "https://lgwxyktbpd.execute-api.us-east-2.amazonaws.com/prod/",
  feedServiceEndPoint: "https://d7dl8k2ursld3.cloudfront.net/",
  cloudFrontEndPoint: "https://d7dl8k2ursld3.cloudfront.net/",
  photoPlaceHolderUrl: 'https://social-media-photo-bucket.s3.us-east-2.amazonaws.com/placeholder.png',
}
